---
continue_on_error: false
doublestar: false
exclude: []
extensions:
- yaml
- yml
include: []
match_type: standard
output_format: default
regex_exclude: []
formatter:
  #array_indent: 0 # = indent, not used if indentless_arrays == true
  disallow_anchors: false
  drop_merge_tag: false
  eof_newline: true # using editorconfig
  include_document_start: true # false
  indent: 2
  indent_root_array: false
  indentless_arrays: true # false
  max_line_length: 0
  pad_line_comments: 1
  retain_line_breaks: true # false
  retain_line_breaks_single: true # false
  scan_folded_as_literal: true # false
  strip_directives: false
  trim_trailing_whitespace: false # rely on editorconfig instead of this
  type: basic
