[tool.mypy]
strict = true
mypy_path = "./venv/Lib/site-packages"
warn_unused_configs = true


# pycodestyle only looks at setup.cfg?
#[tool.pycodestyle]
## E203: black is dealing with the whitespace correctly, no need for diags
#ignore = "E203"

[tool.autopep8]
max_line_length = 79

[tool.black]
line-length = 79
