---
name: Data Generator
on:
  workflow_call:
    inputs:
      data_script:
        required: true
        type: string
      data_files:
        required: true
        type: string
      commit_message:
        required: true
        type: string

permissions:
  contents: write

jobs:
  data-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: npm

    - name: Generate Data
      run: |
        npm install
        ${{ inputs.data_script }}

    - name: Check Status
      run: |
        st=$(git status --short);
        if [[ -n $st ]]; then
          echo "NEW_DATA=true" >> "$GITHUB_ENV";
        else
          echo "NEW_DATA=false" >> "$GITHUB_ENV";
        fi

    - name: Commit+Push
      if: ${{ env.NEW_DATA == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.data_files }}
        git commit -m ${{ inputs.commit_message }}
        git push

...
