---
name: Data-gen Prime Resurgence
on:
  workflow_dispatch:
  schedule:
  # At 18:03 UTC on Thursday
  - cron: '3 18 * * 4'

permissions:
  contents: write

jobs:
  data-gen:
    uses: ./.github/workflows/data-generator.yml
    with:
      data_script: |-
        node src/gen_prime_resurgence.js
      data_files: >-
        _data/prime_resurgence.yml
      commit_message: "data-gen: prime-resurgence"
    secrets: inherit
...
