---
name: Data-gen Void Trader
on:
  workflow_dispatch:
  schedule:
  # At 15:03 UTC on Fridays
  - cron: '3 15 * * 5'
  - cron: '3 15 * * 0'

permissions:
  contents: write

jobs:
  data-gen:
    uses: ./.github/workflows/data-generator.yml
    with:
      data_script: |-
        node src/gen_void_trader.js
      data_files: >-
        _data/void_trader.yml
      commit_message: "data-gen: void_trader"
    secrets: inherit
...
